baseURL: "https://yliu.tech/" 
title: Yiqiang Adrian Liu
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

params:
    description: ""
    author: Yiqiang Adrian Liu
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: false
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowAllPagesInArchive: false
    MainSections: ["books","courses","papers","data"]
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Yiqiang Adrian Liu
          subtitle: "I am a computer engineer with expertise in software development, computational methods, and data-driven problem-solving. With a strong foundation in programming and system design, I specialize in building scalable digital solutions and optimizing workflows through efficient code. Passionate about technology and innovation, I leverage my knowledge to create impactful engineering solutions. Fluent in multiple languages, I enjoy collaborating in global environments to drive technical excellence."
          imageUrl: "picture.jpeg"
          imageWidth: 160
          imageHeight: 160

    socialIcons:
        - name: CV
          url: cv.pdf
        - name: Email
          url: mailto:contact@yliu.tech
        - name: GitHub
          url: https://github.com/jumpjumptiger007
        - name: LinkedIn
          url: https://www.linkedin.com/in/adrian-liu-abovea


    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Yiqiang Adrian Liu"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
